# Generated by Django 5.0.1 on 2024-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\MY PROJECT\\E_Survey\\static\\Imagesŵ.jpg'),
        ),
    ]
