# Generated by Django 5.0.1 on 2024-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_survey_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
