# Generated by Django 5.0.1 on 2024-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_survey_app', '0002_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
