# Generated by Django 5.0.1 on 2024-04-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_survey_app', '0004_user_delete_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Sign',
        ),
    ]
