# Generated by Django 5.0.1 on 2024-04-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_survey_app', '0005_rename_user_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign',
            new_name='User',
        ),
    ]
