# Generated by Django 5.0.1 on 2024-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_survey_app', '0006_rename_sign_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
